//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace losk_3.BasaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.ServiceRequests = new HashSet<ServiceRequests>();
            this.User = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Midle_name { get; set; }
        public System.DateTime Born_date { get; set; }
        public int Gender { get; set; }
        public int Position_at_work { get; set; }
        public decimal Wages { get; set; }
        public decimal Passport_serial { get; set; }
        public decimal Passport_number { get; set; }
        public string Registration { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Job_title Job_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequests> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
