//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace losk_3.BasaSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telecom_loskEntities : DbContext
    {
        public telecom_loskEntities()
            : base("name=telecom_loskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Installations> Installations { get; set; }
        public virtual DbSet<Job_title> Job_title { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<ServiceRequests> ServiceRequests { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaxReporting> TaxReporting { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ServiceStats> ServiceStats { get; set; }
    }
}
